---
# handlers file for pgpool2
- name: Make sure pgpool2 service unit is reloaded
  ansible.builtin.systemd:
    state: reloaded
    name: pgpool2
  listen: "reload pgpool service"

- name: Make sure postgresql service unit is reloaded
  ansible.builtin.systemd:
    state: reloaded
    name: postgresql
  listen: "reload postgres service"

