---
# tasks file for pgpool2
- name: Install required packages
  ansible.builtin.package:
    name:
      - postgresql
      - pgpool2
    state: present
  tags:
    - install_packages

- name: Ensure required directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0755
    owner: postgres
  loop:
    - "/var/log/pgpool/oiddir"

- name: Make sure postgresql service is enabled
  ansible.builtin.systemd:
    state: started
    name: postgresql
    enabled: yes

- name: Make sure pgpool2 service is enabled
  ansible.builtin.systemd:
    state: started
    name: pgpool2
    enabled: yes

- name: Update postgres max conns to support pgpool2
  ansible.builtin.lineinfile:
    path: /etc/postgresql/12/main/postgresql.conf
    regexp: '^max_connections ='
    line: max_connections = 1001
    backup: yes
  notify: "reload postgres service"

- name: Deploy pgpool2 high performance config
  ansible.builtin.copy:
    src: pgpool.conf
    dest: "/etc/pgpool2/pgpool.conf"
    backup: yes
    mode: 0640
    group: postgres
  notify: "reload pgpool service"
