---
# tasks file for pgpool2
- name: Install required packages
  ansible.builtin.package:
    name:
      - postgresql
      - pgpool2
    state: present
  tags:
    - install_packages

- name: Ensure required directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: no
    mode: 0750
    owner: postgres
  loop:
    - "/var/log/pgpool/oiddir"

- name: Deploy high performance config
  ansible.builtin.copy:
    src: pgpool.conf
    dest: "/etc/pgpool2/pgpool.conf"
    backup: yes
    mode: 0640
    group: postgres

- name: Make sure a service unit is running
  ansible.builtin.systemd:
    state: started
    name: pgpool2
    enabled: yes