---
- name: all the things
  hosts: "{{ target | default('all') }}"
  gather_facts: yes
  become: no

  tasks:
    - name: display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 4
