---
- name: all the things
  hosts: "{{ target | default('all') }}"
  remote_user: red
  
  tasks:
    - name: display all hostvars, for all hosts, when a variable defined against host matches
      when: testvar_host == 'ic4lights'
      debug:
        var: hostvars

    - name: display a fact via hostvars, applicable to this host only
      debug:
        var: hostvars[inventory_hostname]['ansible_ssh_user']

    - name: display locally scoped variable
      debug:
        var: group_names
