---
- name: all the things
  hosts: "{{ target | default('all') }}"
  remote_user: red
  
  tasks:
    - name: display all hostvars, for all hosts, when a variable defined against host matches
      when:
        - testvar_host is defined
        - testvar_host == 'ic4lights'
      #ignore_errors: true
      debug:
        var: hostvars

    - name: display a fact via hostvars, for this host
      debug:
        var: hostvars[inventory_hostname]['default_ipv4']['macaddress']

    - name: display locally scoped variable, group_names
      debug:
        var: group_names

    - name: display locally scoped variable, conversion test
      debug:
        var: default_ipv4.macaddress
