---
- name: all the things
  hosts: "{{ target | default('all') }}"
  remote_user: red
  
  tasks:
    - name: display all hostvars, for all hosts, when a variable defined against host matches
      when:
        - testvar_host is defined
        - testvar_host == 'ic4lights'
      #ignore_errors: true
      debug:
        var: hostvars

    - name: display a fact via hostvars, for this host (or other in first group)
      debug:
        var: hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['macaddress']

    - name: display locally scoped variable, group_names
      debug:
        var: group_names

    - name: display locally scoped variable, conversion test
      debug:
        var: ansible_facts['default_ipv4']['macaddress']

    - name: Run the command if "foo" is defined
      ansible.builtin.shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - name: Fail if "bar" is undefined
      ansible.builtin.fail: msg="Bailing out. This play requires 'bar'"
      when: bar is undefined
      ignore_errors: true

    - name: Register a variable
      ansible.builtin.shell: cat /etc/redhat-release
      register: release

    - name: Use the variable in conditional statement
      ansible.builtin.shell: echo "found a rhel 8"
      when: release.stdout.find('8.') != -1
