---
- name: ACL Test
  hosts: rhel9
  gather_facts: yes
  become: no

  tasks:
    - name: Obtain the ACL for a specific file
      ansible.posix.acl:
        path: /etc/redhat-release
      register: acl_info

    - name: Print return information from the previous task
      ansible.builtin.debug:
        var: acl_info
        verbosity: 0
