- name: Config Vim with plugins backed by role
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: yes
  become: no

  tasks:
    - name: Configure Vim using role
      import_role:
        name: vim
